Could not find platform independent libraries <prefix>
Could not find platform dependent libraries <exec_prefix>
Consider setting $PYTHONHOME to <prefix>[:<exec_prefix>]
ImportError: No module named site
Job start at Sun Feb  7 21:53:13 CET 2021
Running job on machine Linux b7g24n0579.cern.ch 3.10.0-957.1.3.el7.x86_64 #1 SMP Thu Nov 29 14:49:43 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux, host b7g24n0579.cern.ch
============================================================
$PWD=/pool/condor/dir_6729
$JOBID=1885128
$TASKID=16
$HOSTNAME=b7g24n0579.cern.ch
$TASKCMD=/afs/cern.ch/work/l/lvigilan/TauWork/CMSSW_10_6_17_patch1/src/TauFW/PicoProducer/python/processors/picojob.py -y 2018 -d 'data' -c etau -M ModuleETau --copydir /eos/home-l/lvigilan/output_ETauFR/2018/etau/EGamma_Run2017B -t _etau_16 --opt 'jec=False' -i root://cms-xrd-global.cern.ch//store/data/Run2018B/EGamma/NANOAOD/Nano25Oct2019-v1/60000/C61D3EFD-DC56-7F41-B028-39F3FA070B13.root root://cms-xrd-global.cern.ch//store/data/Run2018B/EGamma/NANOAOD/Nano25Oct2019-v1/60000/DCE02FC3-F0CE-6740-A953-CB969DDD02B5.root root://cms-xrd-global.cern.ch//store/data/Run2018B/EGamma/NANOAOD/Nano25Oct2019-v1/60000/E197F2FA-C05F-FB47-A56A-2ABC232A05D7.root root://cms-xrd-global.cern.ch//store/data/Run2018B/EGamma/NANOAOD/Nano25Oct2019-v1/60000/E4BC7705-C2F2-1D4D-BBD5-3E375685BA51.root root://cms-xrd-global.cern.ch//store/data/Run2018B/EGamma/NANOAOD/Nano25Oct2019-v1/60000/F9E37363-DC57-164C-9A85-F4B1E25F3185.root
$WORKDIR=/pool/condor/dir_6729
>>> cd /afs/cern.ch/work/l/lvigilan/TauWork/CMSSW_10_6_17_patch1/src
>>> eval `scramv1 runtime -sh`
>>> cd /pool/condor/dir_6729
$PWD=/pool/condor/dir_6729
>>> /afs/cern.ch/work/l/lvigilan/TauWork/CMSSW_10_6_17_patch1/src/TauFW/PicoProducer/python/processors/picojob.py -y 2018 -d 'data' -c etau -M ModuleETau --copydir /eos/home-l/lvigilan/output_ETauFR/2018/etau/EGamma_Run2017B -t _etau_16 --opt 'jec=False' -i root://cms-xrd-global.cern.ch//store/data/Run2018B/EGamma/NANOAOD/Nano25Oct2019-v1/60000/C61D3EFD-DC56-7F41-B028-39F3FA070B13.root root://cms-xrd-global.cern.ch//store/data/Run2018B/EGamma/NANOAOD/Nano25Oct2019-v1/60000/DCE02FC3-F0CE-6740-A953-CB969DDD02B5.root root://cms-xrd-global.cern.ch//store/data/Run2018B/EGamma/NANOAOD/Nano25Oct2019-v1/60000/E197F2FA-C05F-FB47-A56A-2ABC232A05D7.root root://cms-xrd-global.cern.ch//store/data/Run2018B/EGamma/NANOAOD/Nano25Oct2019-v1/60000/E4BC7705-C2F2-1D4D-BBD5-3E375685BA51.root root://cms-xrd-global.cern.ch//store/data/Run2018B/EGamma/NANOAOD/Nano25Oct2019-v1/60000/F9E37363-DC57-164C-9A85-F4B1E25F3185.root
Error in <TGClient::TGClient>: can't open display "localhost:40.0", switching to batch mode...
 In case you run from a remote ssh session, reconnect with ssh -Y
--------------------------------------------------------------------------------
>>> era          = '2018'
>>> year         = 2018
>>> channel      = 'etau'
>>> modname      = 'ModuleETau'
>>> dtype        = 'data'
>>> kwargs       = {'dtype': 'data', 'verb': 0, 'era': '2018', 'jec': False, 'year': 2018}
>>> maxevts      = None
>>> outdir       = '.'
>>> copydir      = '/eos/home-l/lvigilan/output_ETauFR/2018/etau/EGamma_Run2017B'
>>> infiles      = ['root://cms-xrd-global.cern.ch//store/data/Run2018B/EGamma/NANOAOD/Nano25Oct2019-v1/60000/C61D3EFD-DC56-7F41-B028-39F3FA070B13.root', 'root://cms-xrd-global.cern.ch//store/data/Run2018B/EGamma/NANOAOD/Nano25Oct2019-v1/60000/DCE02FC3-F0CE-6740-A953-CB969DDD02B5.root', 'root://cms-xrd-global.cern.ch//store/data/Run2018B/EGamma/NANOAOD/Nano25Oct2019-v1/60000/E197F2FA-C05F-FB47-A56A-2ABC232A05D7.root', 'root://cms-xrd-global.cern.ch//store/data/Run2018B/EGamma/NANOAOD/Nano25Oct2019-v1/60000/E4BC7705-C2F2-1D4D-BBD5-3E375685BA51.root', 'root://cms-xrd-global.cern.ch//store/data/Run2018B/EGamma/NANOAOD/Nano25Oct2019-v1/60000/F9E37363-DC57-164C-9A85-F4B1E25F3185.root']
>>> outfname     = './pico_etau_etau_16.root'
>>> branchsel    = '/afs/cern.ch/work/l/lvigilan/TauWork/CMSSW_10_6_17_patch1/python/TauFW/PicoProducer/processors/keep_and_drop_skim.txt'
>>> json         = '/afs/cern.ch/work/l/lvigilan/TauWork/CMSSW_10_6_17_patch1/src/TauFW/PicoProducer/data/json/2018/Cert_314472-325175_13TeV_PromptReco_Collisions18_JSON.txt'
>>> prefetch     = False
>>> cwd          = /pool/condor/dir_6729
--------------------------------------------------------------------------------

   ################
   #  ModuleETau  #
   ################

Loading TreeProducerETau for './pico_etau_etau_16.root'
--------------------------------------------------------------------------------
>>> filename     = './pico_etau_etau_16.root'
>>> year         = 2018
>>> dtype        = 'data'
>>> channel      = 'etau'
>>> ismc         = False
>>> isdata       = True
>>> isembed      = False
>>> tes          = None
>>> tessys       = None
>>> ltf          = 1.0
>>> jtf          = 1.0
>>> dotoppt      = False
>>> dozpt        = False
>>> dojec        = False
>>> dojecsys     = False
>>> dotight      = False
>>> jetCutPt     = 30
>>> bjetCutEta   = 2.7
>>> tauwp        = 0
>>> eleCutPt     = 33
>>> eleCutEta    = 2.1
>>> tauCutPt     = 20
>>> tauCutEta    = 2.3
Pre-select 17294 entries out of 17294 (100.00%)
Processed    10000/   17294 entries, 57.82% (elapsed time    17.1s, curr speed    0.586 kHz, avg speed    0.586 kHz), accepted      317/   10001 events ( 3.17%)
Error in <TNetXNGFile::Open>: [ERROR] Server responded with an error: [3010] Unable to access - public access level restriction /eos/vbc/experiments/cms/store/data/Run2018B/EGamma/NANOAOD/Nano25Oct2019-v1/60000/DCE02FC3-F0CE-6740-A953-CB969DDD02B5.root; Permission denied

Processed 17294 preselected entries from root://cms-xrd-global.cern.ch//store/data/Run2018B/EGamma/NANOAOD/Nano25Oct2019-v1/60000/C61D3EFD-DC56-7F41-B028-39F3FA070B13.root (17294 entries). Finally selected 527 entries
Traceback (most recent call last):
  File "/afs/cern.ch/work/l/lvigilan/TauWork/CMSSW_10_6_17_patch1/src/TauFW/PicoProducer/python/processors/picojob.py", line 111, in <module>
    p.run()
  File "/afs/cern.ch/work/l/lvigilan/TauWork/CMSSW_10_6_17_patch1/python/PhysicsTools/NanoAODTools/postprocessing/framework/postprocessor.py", line 163, in run
    inTree = inFile.Get("Events")
ReferenceError: attempt to access a null-pointer

Job complete at Sun Feb  7 21:55:49 CET 2021
Took 2 minutes 36 seconds040 (1885128.016.000) 02/07 21:55:49 Finished transferring output files
...
005 (1885128.016.000) 02/07 21:55:49 Job terminated.
	(1) Normal termination (return value 0)
		Usr 0 00:00:09, Sys 0 00:00:01  -  Run Remote Usage
		Usr 0 00:00:00, Sys 0 00:00:00  -  Run Local Usage
		Usr 0 00:00:09, Sys 0 00:00:01  -  Total Remote Usage
		Usr 0 00:00:00, Sys 0 00:00:00  -  Total Local Usage
	6798  -  Run Bytes Sent By Job
	9877  -  Run Bytes Received By Job
	6798  -  Total Bytes Sent By Job
	9877  -  Total Bytes Received By Job
	Partitionable Resources :    Usage  Request Allocated 
	   Cpus                 :        0        1         1 
	   Disk (KB)            :       78        1    296518 
	   Memory (MB)          :       10     2000      2000 
...
